export const SELECT_TEMPLATE = 'DASHBOARD_SELECT_TEMPLATE';
export const SET_TEMPLATE_NAME = 'DASHBOARD_SET_TEMPLATE_NAME';
export const SET_ITEMS = 'DASHBOARD_SET_ITEMS';
export const SET_TEMPLATES = 'DASHBOARD_SET_TEMPLATES';
export const SHOW_ADD_ITEM = 'DASHBOARD_SHOW_ADD_ITEM';
export const SHOW_ADD_TEMPLATE = 'DASHBOARD_SHOW_ADD_TEMPLATE';
