export const LOAD = 'DASHBOARD_LOAD';
export const PRE_SELECT_TEMPLATE = 'DASHBOARD_PRE_SELECT_TEMPLATE';
export const SELECT_TEMPLATE = 'DASHBOARD_SELECT_TEMPLATE';
export const SET_TEMPLATES = 'DASHBOARD_SET_TEMPLATES';
export const SHOW_ADD_ITEM = 'DASHBOARD_SHOW_ADD_ITEM';
export const SHOW_ADD_TEMPLATE = 'DASHBOARD_SHOW_ADD_TEMPLATE';
